### ISSUE TITLE
Advice on code

### ISSUE THREAD

**Issue by NobodyXu** [HubertPastyrzak/Bashmash#5]
I've just read `src/integer/Integer.h` and found its code is plain bad:
 - `using namespace std;` this should never appear in any C++ project
 - `Integer(Integer* x);` a copy constructor should take `Integer(const Integer&)`
 - `Integer(string x);` copies `string`.
   <br>Use `Integer(const std::string &x);` instead.
 - The functions below:
   
   ```
   bool lessThan(Integer* x);            
   bool lessThanOrEqualTo(Integer* x);   
   bool equalTo(Integer* x);             
   bool greaterThan(Integer* x);         
   bool greaterThanOrEqualTo(Integer* x);
   ```
   
   should be implemented using operator overloading `friend bool operator < (const Integer &x, const Integer &y) {}`.
 - `long long* fields;` raw pointer shouldn't be used in modern C++.
   <br>In C++11 and above, [`std::unique_ptr`](https://en.cppreference.com/w/cpp/memory/unique_ptr) is introduced to avoid this and automatically free it in its destructor.

**Comment by HubertPastyrzak** [comment]
Not gonna lie, I'm a newbie to modern C++, and I have to admit that this part was written quite in a hurry. ;P
Anyway, thank you for your advice! :D

**Comment by NobodyXu** [comment]
Just as an advice:

issues are usually used as tickets to tract the status of the problem.

It usually isn’t closed until the problem is resolved.

**Comment by NobodyXu** [comment]
Contributors also often reference issues in their commits or merge request (PR) by #5.

Check [Mastering Issues](https://guides.github.com/features/issues/) for more info.

**Comment by HubertPastyrzak** [comment]
Oh, okay. That makes sense, I'll remember next time. Thanks for the advice! :)
